frontend/components/ClockInCard.jsx, frontend/components/ClockOutCard.jsx
This PR introduces the `ClockInCard` component, which provides users with details about their clock-in time, subscription status, and any required actions upon arrival at the hub. The component dynamically adjusts its content based on different user scenarios.  
- **User Information Display**: Shows user avatar, name, email, subscription status, and expiry date.  
- **Clock-In Time**: Displays the time a user clocked into the hub.  
- **Conditional Rendering**:  
- If a **payment is required**, prompts the user to complete outstanding payments.  
- If the **user tries to clock in twice**, displays an error message.  
- Otherwise, shows the successful clock-in time.  
- **Responsive Design**: Ensures proper layout across different screen sizes using Tailwind CSS.  
- **Navigation Button**: …
=> created the clockin card component

frontend/components/ClockInCard.jsx
This PR introduces the `ClockInCard` component, which provides users with details about their clock-in time, subscription status, and any required actions upon arrival at the hub. The component dynamically adjusts its content based on different user scenarios.  
- **User Information Display**: Shows user avatar, name, email, subscription status, and expiry date.  
- **Clock-In Time**: Displays the time a user clocked into the hub.  
- **Conditional Rendering**:  
- If a **payment is required**, prompts the user to complete outstanding payments.  
- If the **user tries to clock in twice**, displays an error message.  
- Otherwise, shows the successful clock-in time.  
- **Responsive Design**: Ensures proper layout across different screen sizes using Tailwind CSS.  
- **Navigation Button**: …
=>  Implement ClockInCard Component

backend/.eslintrc.js, backend/.gitignore, backend/.prettierrc, backend/README.md, backend/nest-cli.json, backend/package-lock.json, backend/package.json, backend/src/app.controller.spec.ts, backend/src/app.controller.ts, backend/src/app.module.ts, backend/src/app.service.ts, backend/src/auth/auth.controller.spec.ts, backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/auth/dto/create-auth.dto.ts, backend/src/auth/dto/update-auth.dto.ts, backend/src/auth/entities/auth.entity.ts, backend/src/main.ts, backend/test/app.e2e-spec.ts, backend/test/jest-e2e.json, backend/tsconfig.build.json, backend/tsconfig.json
This PR sets up a basic authentication system in a NestJS project, implementing user registration and login functionality with JWT-based authentication.
- Created an `auth` module to handle authentication-related logic.
- The `AuthModule` includes the `AuthService` for managing JWT token generation, password hashing, and validation, and the `AuthController` for handling registration and login routes.
- Implemented a `POST /auth/register` route to allow users to register by providing a `username` and `password`.
- Passwords are hashed using `bcryptjs` before storing them (mocked for this PR; database integration can be done later).
- Implemented a `POST /auth/login` route to authenticate users. This route compares the provided password with the stored (hashed) password and returns a JWT …
=> feature commit

frontend/components/layouts/adminLayout.jsx
This PR implements a responsive admin layout system with core navigation structure, page scaffolding, and foundational search functionality to serve as the base for all admin interfaces.
- **SidebarNavigation**: Responsive collapsible sidebar with icon support  
- **AdminHeader**: Page header with breadcrumb-style titles and user controls  
- **SearchBar**: Reusable search component with icon integration  
- **NavItem**: Dynamic navigation link component with active state tracking  
- *Mobile-First Sidebar*: Collapsible navigation using Headless UI Dialog  
- *Active Route Highlighting*: Automatic navigation state management  
- *Search Foundation*: UI-ready search input with icon integration  
- *User Controls*: Notification bell, settings gear, and profile dropdown  
- *Responsive …
=> Admin Layout with All Admin Pages and Search Functionality

frontend/app/users/page.js
Implement Users UI Page for ManageHub Dashboard
📌 Overview
This PR implements the Users Page in the ManageHub dashboard to display and manage registered users in a clean, responsive interface. This is a core part of the system, allowing administrators to easily view user data and perform user-related actions.
✅ Tasks Done
[x] Created a protected UsersPage under /app/dashboard/users/page.jsx
[x] Built a responsive UserTable component to display user data
[x] Implemented a reusable UserRow component for table rows
[x] Added columns: Full Name, Email, Role, Status, Actions
[x] Implemented action buttons: Edit, Delete, View
[x] Added an "Add New User" button at the top of the page
[x] Styled all components using TailwindCSS for responsiveness
[x] Used mock data for initial user list (to be …
=>  Implement Users UI Page for ManageHub Dashboard

frontend/app/monitoring/page.js
This PR implements the Admin Monitoring UI Page for ManageHub, a hub management system for tech hubs. The page is a crucial part of the Admin Dashboard, designed to give administrators real-time insights into hub usage, user activity, workspace availability, and biometric tracking. It includes responsive layouts, interactive components, and seamless integration with backend services.
🎯 Features Implemented
UI Design & Responsiveness
Designed a modern and responsive layout consistent with the ManageHub branding.
Optimized the UI for both desktop and mobile views using TailwindCSS.
Core Components
User Activity Monitoring
Display of currently active users.
Includes activity timestamps and real-time activity labels (e.g., "Using Workspace", "Clocked In").
Workspace Availability
Visual …
=> Implement Admin Monitoring UI Page for ManageHub

frontend/app/user-profile/page.js, frontend/components/CustomToast.jsx, frontend/components/EmailVerification.jsx, frontend/components/PersonalDetailsForm.jsx, frontend/components/PunctualityLeaderboard.jsx, frontend/components/RecentActivities.jsx, frontend/components/SpacesCard.jsx, frontend/components/TextError.jsx, frontend/components/TimeOfArrival.jsx
This PR delivers the implementation of the **User Profile UI Page** and four key **frontend components** — `PunctualityLeaderboard`, `PersonalDetailsForm`, `EmailVerification`, and `CustomToast` — for the **ManageHub** application. These elements lay the groundwork for both user account management and core app functionality in a coworking and tech hub management platform.
---
- Designed a **modern and responsive user profile page** using TailwindCSS utility classes
- Layout includes:
- User Avatar (placeholder image)
- Full Name
- Email Address
- Optional Phone Number
- Role (display only, e.g., Admin/Member)
- Buttons: Edit Profile (non-functional), Change Password (link), Logout
- Styled with `rounded-2xl`, `p-4+`, and consistent with overall ManageHub theme
- Fully **responsive** …
=> Implement User Profile UI Page and Core Frontend Components for ManageHub

frontend/app/subscription/page.js, package-lock.json
#17 
Admin Subscription UI Page for ManageHub
Description
The Admin Subscription UI page for the ManageHub platform has been successfully implemented. The page allows admins to manage tenant subscription plans, add users, handle billing preferences, and simulate key actions such as sending reminders and completing payments.
✅ Completed Features
Responsive subscription dashboard with empty and populated states.
Interactive modals for:
Adding individual users or teams
Completing payment via card, bank transfer, or cash
Verifying hub user identity
Sending renewal reminders
Table displaying:
Subscribed users, space allocations, plan types, expiry dates, and statuses
Filtering and searching capability.
Toggle for team/individual input forms with Formik + Yup validation.
Toast notifications for …
=> feat: Subscription ui

frontend/app/admin/page.js
=> Add user profile page components

frontend/app/spaces/page.js
This PR introduces the **UI layout and components** for the **Spaces pages** in the ManageHub application. These pages will be central to how users interact with coworking spaces, view available spaces, and manage or book them (functionality to be implemented later).
At this stage, the focus is on building a clean, responsive, and modular frontend interface consistent with the overall design system of ManageHub.
---
The following views/components are included:
- **Spaces Overview Page** – A grid or list displaying all available workspaces
- **Individual Space Card** – Shows image, name, location, description, and status (e.g., available, booked)
- **Topbar Filters** – Basic UI for filtering spaces by type or availability (non-functional for now)
- **Empty State Component** – Displayed …
=> Created the Spaces Pages UI for ManageHub

frontend/app/complaints/page.js
- Built an admin UI to display and manage user complaints
- Showed key details: user name, title, description, date, and status
- Added filtering by status/date and keyword search
- Enabled viewing full complaint details and updating status
- Designed a clean, modern, and responsive layout for all screen sizes
=> feat: implemented responsive Complaints Admin UI 

frontend/utils/axios.js, frontend/utils/validationShema.js
Added the validation schema and axios instance for the project in the utils folder.
closes #20
=> created the validation schema for the project

frontend/components/AdditionalDetailsForm.jsx, frontend/components/AttendanceChart.jsx, frontend/components/H3.jsx, frontend/components/P.jsx
=> added some core components

backend/package-lock.json, backend/package.json, backend/src/auth/admin.guard.ts, backend/src/monitoring/create-monitoring.dto.ts, backend/src/monitoring/monitoring.controller.spec.ts, backend/src/monitoring/monitoring.controller.ts, backend/src/monitoring/monitoring.entity.ts, backend/src/monitoring/monitoring.module.ts, backend/src/monitoring/monitoring.service.spec.ts, backend/src/monitoring/monitoring.service.ts
Created the Monitoring Module for Tracking Workspace Usage and Staff Attendance
closes #38
=> Create Monitoring Module for Tracking Workspace Usage and Staff Attendance

backend/src/subscription/dto/create-subscription-plan.dto.ts, backend/src/subscription/dto/subscribe.dto.ts, backend/src/subscription/entities/subscription-plan.entity.ts, backend/src/subscription/entities/user-subscription.entity.ts, backend/src/subscription/subscription.controller.ts, backend/src/subscription/subscription.module.ts, backend/src/subscription/subscription.scheduler.ts, backend/src/subscription/subscription.service.ts
This PR introduces a complete **Subscription Module** to manage user memberships for different workspace access plans (daily, weekly, monthly). The system ensures that each user can only maintain **one active subscription at a time**, with automatic expiration handling.
---
* **`SubscriptionModule`**: New module encapsulating subscription-related logic.
* **`SubscriptionService`**: Handles business logic for plans and user subscriptions.
* **`SubscriptionController`**: Defines REST API endpoints for managing subscriptions.
* **`SubscriptionPlan`**
* `id`: Unique identifier
* `name`: Plan name (e.g., Daily, Weekly, Monthly)
* `price`: Cost of the plan
* `duration`: Duration in days
* `features`: Array of feature strings
* `isActive`: Toggle for availability
* **`UserSubscription`**
* `id`: …
=> created the subscriptions implementation

backend/src/app.module.ts, backend/src/audit-log/audit-log.controller.ts, backend/src/audit-log/audit-log.module.ts, backend/src/audit-log/audit-log.service.spec.ts, backend/src/audit-log/audit-log.service.ts, backend/src/audit-log/entities/audit-log.entity/audit-log.entity.ts, backend/src/clock-in/clock-in.controller.ts, backend/src/clock-in/clock-in.module.ts, backend/src/clock-in/clock-in.service.ts, backend/src/clock-in/dto/create-clock-in.dto.ts, backend/src/clock-in/dto/update-clock-in.dto.ts, backend/src/clock-in/entities/clock-in.entity.ts, backend/src/workspace/dto/create-workspace.dto.ts, backend/src/workspace/dto/update-workspace.dto.ts, backend/src/workspace/entities/workspace.entity.ts, backend/src/workspace/workspace.controller.ts, backend/src/workspace/workspace.module.ts, backend/src/workspace/workspace.service.ts
close: #48
Here’s a descriptive summary of the issues i’ve solved so far while building the ManageHub audit logging system:
✅ 1. Audit Logging System Architecture
You designed and implemented a centralized AuditLogModule to track critical system-wide events such as workspace creation and user clock-ins. This enables:
Accountability: Every key action is traceable to an actor.
Debugging: Developers can investigate historical actions during issues.
Security & Compliance: Helps meet audit trail requirements.
✅ 2. Integration with Clock-In Module
You created a ClockinModule with:
Entity to store clock-in records
Controller to expose a POST endpoint
Service to handle logic and log each clock-in
Each clock-in is now automatically logged as an audit event:
Action: USER_CLOCKED_IN
Actor: userId …
=> implementation of Audit logging system for tracking system wide events

backend/src/notification/dto/create-notification.dto.ts, backend/src/notification/dto/update-notification.dto.ts, backend/src/notification/entities/notification.entity.ts, backend/src/notification/notification.controller.spec.ts, backend/src/notification/notification.controller.ts, backend/src/notification/notification.module.ts, backend/src/notification/notification.service.spec.ts, backend/src/notification/notification.service.ts, backend/src/notification/websocket.gateway.ts
=> Implement Notification Module with DTOs, Controller, Service, and WebSocket support

backend/src/app.module.ts, backend/src/common/decorators/roles.decorator.ts, backend/src/common/guards/roles.guards.ts, backend/src/roles/permission.entity.ts, backend/src/roles/role.entity.ts, backend/src/roles/role.enum.ts, backend/src/workspace/workspace.controller.ts
Added @Roles() decorator and RolesGuard
Defined roles: admin, hub-manager, staff, user
Applied role checks to workspace and analytics routes
Set up role and permission entities for dynamic access control
Closes #46
=> feat(auth): add role-based access control with guards and DB support

backend/src/app.module.ts, backend/src/businesses/businesses.controller.ts, backend/src/businesses/businesses.module.ts, backend/src/businesses/businesses.service.ts, backend/src/businesses/dto/create-business.dto.ts, backend/src/businesses/dto/update-business.dto.ts, backend/src/businesses/entities/business.entity.ts
Implements a comprehensive businesses management module for the tech hub with full CRUD operations to track businesses operating within the hub.
- **Complete CRUD Operations**: Create, Read, Update, Delete businesses
- **Contact Information Management**: Email, phone, address, contact person details
- **Services Tracking**: Array of services offered by each business
- **Website Links**: Store and manage business website URLs
- **Category Filtering**: Filter businesses by category (e.g., Software Development)
- **Status Management**: Activate/deactivate businesses
- **Advanced Filtering**: Filter by active status and category
- **Entity**: Business entity with TypeORM decorators
- **DTOs**: CreateBusinessDto and UpdateBusinessDto with validation ready
- **Service**: BusinessesService with …
=> feat: implement businesses module with full CRUD operations

backend/src/app.module.ts, backend/src/internal-notes/dto/create-internal-note.dto.ts, backend/src/internal-notes/internal-note.entity.ts, backend/src/internal-notes/internal-notes.controller.ts, backend/src/internal-notes/internal-notes.module.ts, backend/src/internal-notes/internal-notes.service.ts
Added internal notes feature for admin-only access
Closes #81
=> feat: add internal notes module for admin-only user annotations

backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/device-maintenance/device-maintenance.controller.ts, backend/src/device-maintenance/device-maintenance.model.ts, backend/src/device-maintenance/device-maintenance.module.ts, backend/src/device-maintenance/device-maintenance.service.ts, backend/src/device-maintenance/dto/create-device.dto.ts, backend/src/device-maintenance/dto/create-maintenance.dto.ts, backend/src/device-maintenance/dto/update-device-maintenance.dto.ts, backend/src/device-maintenance/entities/device-maintenance.entity.ts
Closes #97 - Device Maintenance Scheduler Implementation
Overview
Implemented a comprehensive device maintenance scheduler module that allows tracking and scheduling regular maintenance for hardware devices like routers, projectors, printers, and other IT equipment.
Features Added
Device Management: Full CRUD operations for hardware devices with detailed tracking
Maintenance Scheduling: Create, update, and track maintenance records with status progression
Automated Scheduling: Automatic calculation of next maintenance dates based on configurable intervals
Priority System: Urgency levels (low, medium, high, critical) based on overdue status and upcoming deadlines
Analytics Dashboard: Comprehensive statistics and reporting capabilities
Workflow Management: Complete maintenance lifecycle …
=> feat: add device maintenance module with CRUD operations

backend/src/energy/controllers/energy-consumption.controller.ts, backend/src/energy/dto/create-energy-consumption.dto.ts, backend/src/energy/dto/energy-summary.dto.ts, backend/src/energy/dto/query-energy.dto.ts, backend/src/energy/energy.module.ts, backend/src/energy/entities/energy-consumption.entity.ts, backend/src/energy/services/energy-consumption.service.ts, backend/src/energy/test/energy-consumption.e2e.spec.ts, backend/src/energy/test/energy-consumption.service.spec.ts, backend/src/energy/test/energy.module.spec.ts
=> energy module

backend/src/Visitor Logs/IntegrationExample/app.module.ts, backend/src/Visitor Logs/IntegrationExample/usageExample.md, backend/src/Visitor Logs/visitor.controller.ts, backend/src/Visitor Logs/visitor.dto.ts, backend/src/Visitor Logs/visitor.entity.ts, backend/src/Visitor Logs/visitor.module.ts, backend/src/Visitor Logs/visitor.service.ts
=> Visitor Logs

backend/src/app.module.ts, backend/src/backups/backup-logger.service.ts, backend/src/backups/backups.module.ts
This PR introduces the Scheduled System Backups Logger as part of task #90. It simulates regular system backup jobs and logs their results without relying on real filesystem or database operations.
✅ Key Features:
Uses @nestjs/schedule to run a backup simulation every minute
Logs:
🔹 Backup job name (e.g., NightlyBackup_2025-07-28)
🔹 Completion time
🔹 Randomized backup size (100–600MB)
🔹 Status (SUCCESS or FAILED, 90% chance success)
🔌 Design Notes:
Operates independently with no external dependencies
Useful for mocking automated backup flows and job monitoring
📌 Next Suggestions:
Add DB storage for backup history
Expose history via /api/backups/history endpoint
Swagger/OpenAPI documentation
Optional trigger/manual backup via admin endpoint
=> Feature: Scheduled System Backups Simulation Logger (#90)

backend/src/lost-and-found/create-lost-item.dto.ts, backend/src/lost-and-found/lost-and-found.controller.ts, backend/src/lost-and-found/lost-and-found.module.ts, backend/src/lost-and-found/lost-and-found.service.spec.ts, backend/src/lost-and-found/lost-and-found.service.ts, backend/src/lost-and-found/lost-item.entity.ts
=> created the lost and found module

backend/package-lock.json, backend/src/app.module.ts, backend/src/checkin-export/services/checkin-export.service.ts, backend/src/energy/entities/energy-consumption.entity.ts, backend/src/location/dto/create-location.dto.ts, backend/src/location/dto/update-location.dto.ts, backend/src/location/entities/location.entity.ts, backend/src/location/location.controller.spec.ts, backend/src/location/location.controller.ts, backend/src/location/location.module.ts, backend/src/location/location.service.spec.ts, backend/src/location/location.service.ts, backend/src/shifts/dto/create-shift.dto.ts, backend/src/shifts/dto/update-shift.dto.ts, backend/src/shifts/entities/shift.entity.ts, backend/src/shifts/shifts.controller.spec.ts, backend/src/shifts/shifts.controller.ts, backend/src/shifts/shifts.module.ts, backend/src/shifts/shifts.service.spec.ts, backend/src/shifts/shifts.service.ts, backend/src/staff/dto/create-staff.dto.ts, backend/src/staff/dto/update-staff.dto.ts, backend/src/staff/entities/staff.entity.ts, backend/src/staff/staff.controller.spec.ts, backend/src/staff/staff.controller.ts, backend/src/staff/staff.module.ts, backend/src/staff/staff.service.spec.ts, backend/src/staff/staff.service.ts
Closes #98 
✅ **Staff Management**
- CRUD operations for staff members
- Unique staff ID validation
- Active/inactive status tracking
- Relationship with shifts
✅ **Location Management** 
- CRUD operations for locations
- Unique location name validation
- Active/inactive status tracking
- Relationship with shifts
✅ **Shift Management**
- CRUD operations for shifts
- Staff and location assignment
- Shift timing and duration tracking
- Status management (scheduled, in_progress, completed, cancelled)
- Overlap detection for staff shifts
- Break duration tracking
- Hours worked calculation
✅ **Advanced Querying**
- Filter shifts by staff member
- Filter shifts by location
- Filter shifts by date range
- Get active staff/locations only
✅ **Data Validation**
- Input validation with …
=> feat:Implement Staff Shifts Scheduler #98

backend/FAQ_IMPLEMENTATION_SUMMARY.md, backend/src/app.module.ts, backend/src/faq/README.md, backend/src/faq/dto/create-faq.dto.ts, backend/src/faq/dto/faq-query.dto.ts, backend/src/faq/dto/update-faq.dto.ts, backend/src/faq/faq.controller.spec.ts, backend/src/faq/faq.controller.ts, backend/src/faq/faq.entity.ts, backend/src/faq/faq.module.ts, backend/src/faq/faq.service.spec.ts, backend/src/faq/faq.service.ts, contract/WORKSPACE_MANAGER_IMPLEMENTATION.md, contract/src/WorkspaceManager.cairo, contract/src/interface.cairo, contract/tests/test_workspace_manager.cairo
This PR introduces a **standalone FAQ Manager module** to handle Frequently Asked Questions (FAQs).  
The module enables admins to create, update, and delete FAQs, while users can fetch and view them.  
It is designed to be **independent** and does not rely on the `user` or `auth` modules.
---
- Implemented a self-contained `FAQModule`.
- Added CRUD operations for managing FAQs:
- **Create FAQ** (Admin only).
- **Update FAQ** (Admin only).
- **Delete FAQ** (Admin only).
- **View FAQs** (Public).
- Designed to be modular and easily integrated with the larger system later.
---
- Standalone module, no dependencies on auth/user modules.
- Simple FAQ entity with:
- `id: number`
- `question: string`
- `answer: string`
- `createdAt: Date`
- `updatedAt: Date`
- Public endpoints for **viewing …
=> Feat faq manager

contract/WORKSPACE_MANAGER_IMPLEMENTATION.md, contract/src/WorkspaceManager.cairo, contract/src/interface.cairo, contract/tests/test_workspace_manager.cairo
This PR introduces the **WorkspaceManager** contract for the **ManageHub StarkNet module**.  
The contract allows creating and managing workspaces, assigning users, enforcing capacity limits, and retrieving workspace details.  
A full test suite using **snforge_std** validates the correctness of workspace creation, user assignment, and capacity enforcement.
---
- Implemented the `WorkspaceManager` Cairo contract with:
- Workspace creation (`create_workspace`)
- User assignment with capacity enforcement (`assign_user_to_workspace`)
- Workspace info retrieval (`get_workspace_info`)
- Added logic to:
- Assign incrementing workspace IDs starting from `1`.
- Enforce **capacity limits** (panic if exceeded).
- Track occupancy and active status.
- Implemented a test suite using **snforge_std** to …
=> Implement Workspace Management Contract with Tests

frontend/middleware.ts
Implements Next.js middleware for authentication and route protection as requested in the requirements.
Closes #175
- ✅ Added `middleware.ts` with authentication logic
- ✅ Public routes: `/`, `/login`, `/register`, `/forgot-password`
- ✅ Protected routes: `/dashboard`, `/users`, `/admin`
- ✅ Redirects authenticated users away from auth pages
- ✅ Redirects unauthenticated users to login with redirect param
- ✅ Excludes API routes, static files, and Next.js internal routes
- ✅ Clean, production-ready TypeScript code
This middleware serves as the foundation for authentication. Role-based access control will be handled at the component level after JWT decoding.
=> feat: implement authentication middleware for route protection

frontend/lib/store/authStore.ts
This pull request introduces a centralized authentication state management system using Zustand, adds persistent authentication across sessions, and updates the login flow to use the new store. It also ensures authentication state is initialized on app startup and propagates async login handling through the component tree.
**Authentication State Management and Persistence**
- Added a new Zustand-based authentication store in `authStore.ts` that manages user state, access tokens, loading state, and provides actions for login, logout, registration, token refresh, and profile updates. The store persists state across sessions and rehydrates on app load.
- Exported the authentication store and related types from a central index for easier imports.
**Authentication Initialization**
- Introduced …
=> feat: implement authentication flow with login and initialization hooks

backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/providers/auth.service.ts, backend/src/users/providers/createUser.provider.ts, backend/src/users/providers/findOneUserByEmail.provider.ts, backend/src/users/providers/findOneUserById.provider.ts, backend/src/users/providers/users.service.ts, backend/src/users/users.module.ts, backend/src/utils/error.ts
- Complete user registration endpoint implementation
- Modular architecture with proper error handling and validation
- Password hashing and duplicate user prevention
- **Error Handling**: Created `utils/error.ts` with `handleError()` function that catches exceptions and re-throws
HttpExceptions or returns InternalServerErrorException
- **Users Module**:
- New `CreateUserProvider` with repository injection, password hashing, and duplicate email detection
- Updated `UsersService` to delegate user creation to the provider
- Added `CreateUserProvider` to module providers array
- **Auth Module**:
- Updated `AuthService` to use `UsersService` for user creation
- Exported `HashingProvider` for dependency injection
- Updated `AuthController` with `POST /auth/register` endpoint
- **Module …
=> feat: BACKEND: Implement User Registration Flow (Auth + Users Modules)

backend/src/auth/auth.module.ts, backend/src/auth/guards/jwt.guard.ts, backend/src/auth/guards/local.guard.ts, backend/src/auth/guards/refreshToken.guard.ts, backend/src/auth/guards/roles.guard.ts, backend/src/auth/strategies/jwt.strategy.ts, backend/src/auth/strategies/jwtRefresh.strategy.ts, backend/src/auth/strategies/local.strategy.ts
=> added all the requested strategies

frontend/app/error.tsx
closes #235  cc @yusuftomilola
=> feat(frontend): add global error boundary and error page

frontend/app/loading.tsx
This pull request introduces a new `Loader` component to the frontend. The component displays a centered loading spinner with a "Loading..." message over a dark, semi-transparent background, providing a visually clear loading state for users.
- UI Components:
* Added a new `Loader` React component in `frontend/app/loading.tsx` that renders a full-screen loading overlay with an animated spinner and message.
This PR closes issue #240 
[Screencast from 2025-09-28 21-03-08.webm](https://github.com/user-attachments/assets/e2b3951d-2706-4799-a343-b973023433f7)
@yusuftomilola 
Please review. Thanks 🙏
=> Global Loading State

frontend/app/not-found.tsx
Implemented a custom 404 error page to handle invalid routes in the application with a modern, user-friendly interface.
* **`app/not-found.tsx`** - Custom 404 page component
✅ **User-Friendly Error Message**
* Large, clear "404" heading with gradient styling
* Friendly "Page Not Found" title
* Helpful descriptive text explaining the error
✅ **Navigation Options**
* "Back to Home" button using `next/link` for homepage navigation
* "Go Back" button using browser history for convenience
* Both buttons fully styled with hover effects
✅ **Modern Design**
* Gradient background (purple-pink for light mode, gray-purple for dark mode)
* Animated icon with pulsing glow effect
* Responsive layout that works on all screen sizes
* Dark theme support for seamless theme switching
✅ **Technical …
=> feat: Implement not found page ui

frontend/components/ui/genericInput.tsx
Added the new input component that supports `type`, `placeholder`, `value`, and `onChange` props also added Tailwind for styling
Added the respective video for reference also I just added the input field on the main `page.tsx` in the video just to check the changes the pushed code doesn't have changes on the main `page.tsx`
resolves #268 
https://github.com/user-attachments/assets/9811392c-165a-4aaf-a38b-c2e87cef4963
=> Fix: Added input component

frontend/app/page.tsx, frontend/components/ui/FeatureCard.tsx, frontend/components/ui/FeaturesSection.tsx
This PR adds the Features Section to the homepage of our Next.js 15 (App Router) project, based on the provided design reference.
- Built with reusable components (FeatureCard, FeaturesSection)
- Matches design with ~90% accuracy, using Lucide React icons
- Fully responsive across desktop, tablet, and mobile
- Includes hover animations + glass morphism effects for modern UI
- Written in TypeScript with clean, reusable code
- Demo video attached showcasing the implementation
https://github.com/user-attachments/assets/006f2406-6fef-475b-9941-91cf0295103a
Closes #261
=> frontend: Implement Features Section On Homepage #261

frontend/components/layout/Container.tsx
=> Fix: FRONTEND: Create a Global Container Component

backend/src/app.module.ts, backend/src/asset-depreciation/__tests__/calculate-depreciation.provider.spec.ts, backend/src/asset-depreciation/__tests__/depreciation-calculations.spec.ts, backend/src/asset-depreciation/asset-depreciation.controller.ts, backend/src/asset-depreciation/asset-depreciation.module.ts, backend/src/asset-depreciation/dto/asset-value.dto.ts, backend/src/asset-depreciation/dto/create-asset.dto.ts, backend/src/asset-depreciation/dto/update-asset.dto.ts, backend/src/asset-depreciation/entities/asset.entity.ts, backend/src/asset-depreciation/providers/asset-depreciation.service.ts, backend/src/asset-depreciation/providers/calculate-depreciation.provider.ts
Implemented Asset Depreciation Module 
Description:
Depreciation will help companies estimate the current value of assets. Implement straight-line depreciation logic.
Expected Behavior:
Stored purchase price, useful life, depreciation method.
Calculated depreciation automatically.
API endpoint to get current depreciated value of asset.
Tasks:
Generated asset-depreciation module.
Defined entity & DTOs.
Wrote service to compute depreciation.
Added endpoint for retrieving values.
closes[#322]
=> Asset modules

frontend/components/auth/EmailLoginForm.tsx, frontend/lib/schemas/forgotPasswordSchema.ts, frontend/lib/schemas/loginSchema.ts, frontend/lib/schemas/registerSchema.ts
Added:
- loginSchema.ts
- registerSchema.ts
- forgotPasswordSchema.ts
Updated:
- EmailLoginForm.tsx
=> login schema, register schema, forgot schema, updated EmailLoginForm

backend/src/asset-maintenance/asset-maintenance.controller.ts, backend/src/asset-maintenance/asset-maintenance.module.ts, backend/src/asset-maintenance/asset-maintenance.service.ts, backend/src/asset-maintenance/asset-maintenence.entity.ts, backend/src/complete-maintenance/complete-maintenance.dto.ts, backend/src/create-maintenance/create-maintenance.dto.ts
This PR introduces the **Asset Maintenance Module** in the system.  
The module enables scheduling and tracking of maintenance activities for assets (e.g., servicing company cars or replacing laptop parts).  
- New database table: `asset_maintenance`  
- Ability to schedule maintenance for assets  
- Ability to mark maintenance tasks as completed  
- Maintenance history per asset  
---
- Generated `asset-maintenance` module (controller, service, entity, DTOs)  
- Created **`AssetMaintenance` entity** with fields:  
- `id`  
- `assetId` (FK)  
- `scheduledDate`  
- `completedDate`  
- `maintenanceType`  
- `notes`  
- Added **DTOs** for:  
- Creating a maintenance schedule  
- Completing a maintenance record  
- Implemented **service methods**:  
- `schedule()` → create a maintenance …
=> Implement asset maintenance module

backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/auth/auth.controller.ts, backend/src/auth/providers/auth.service.ts, backend/src/notifications/dto/create-notification.dto.ts, backend/src/notifications/dto/mark-read.dto.ts, backend/src/notifications/dto/update-notification.dto.ts, backend/src/notifications/entities/notification.entity.ts, backend/src/notifications/notifications.controller.spec.ts, backend/src/notifications/notifications.controller.ts, backend/src/notifications/notifications.module.ts, backend/src/notifications/notifications.service.spec.ts, backend/src/notifications/notifications.service.ts
This PR implements a basic in-app notifications system:
Database entity: [notification.entity.ts](vscode-file://vscode-app/c:/Users/u-adamu/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
DTOs: backend/src/notifications/dto/*
Service: [notifications.service.ts](vscode-file://vscode-app/c:/Users/u-adamu/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
Controller: [notifications.controller.ts](vscode-file://vscode-app/c:/Users/u-adamu/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/workbench.html)
Module registration: [notifications.module.ts](vscode-file://vscode-app/c:/Users/u-ad …
=>  feat(notifications): implement in-app notifications (entity, service, API)

backend/src/app.module.ts, backend/src/countries-currencies/README.md, backend/src/countries-currencies/countries-currencies.controller.ts, backend/src/countries-currencies/countries-currencies.module.ts, backend/src/countries-currencies/countries-currencies.service.ts, backend/src/countries-currencies/dto/create-country.dto.ts, backend/src/countries-currencies/dto/create-currency.dto.ts, backend/src/countries-currencies/dto/create-exchange-rate.dto.ts, backend/src/countries-currencies/dto/update-country.dto.ts, backend/src/countries-currencies/dto/update-currency.dto.ts, backend/src/countries-currencies/dto/update-exchange-rate.dto.ts, backend/src/countries-currencies/entities/country.entity.ts, backend/src/countries-currencies/entities/currency.entity.ts, backend/src/countries-currencies/entities/exchange-rate.entity.ts, backend/src/migrations/1728000000000-CreateCountriesCurrenciesTables.ts
=> Implement Country & Currency Module

backend/src/reporting/department.entity.ts, backend/src/reporting/reporting.controller.ts, backend/src/reporting/reporting.dto.ts, backend/src/reporting/reporting.entity.ts, backend/src/reporting/reporting.module.ts, backend/src/reporting/reporting.service.ts
=> implemented the reporting module

backend/src/inventory-alerts/controllers/inventory-alerts.controller.ts, backend/src/inventory-alerts/dto/alert.dto.ts, backend/src/inventory-alerts/dto/get-alerts.query.dto.ts, backend/src/inventory-alerts/entities/alert.entity.ts, backend/src/inventory-alerts/entities/inventory-item.entity.ts, backend/src/inventory-alerts/inventory-alerts.e2e-spec.ts, backend/src/inventory-alerts/inventory-alerts.module.ts, backend/src/inventory-alerts/inventory-alerts.service.spec.ts, backend/src/inventory-alerts/inventory-alerts.service.ts, backend/src/stock/stock.service.ts, package-lock.json
Adds InventoryItem + Alert entities, InventoryAlertsService (checkItemThreshold, checkAllThresholds, getAlerts), controller GET /inventory/alerts, unit + e2e tests, and integration notes to call checkItemThreshold after stock updates. Closes #327
=> feat(inventory): implement inventory threshold alerts + tests (#327)
